name: Build

on:
  workflow_dispatch:
  #push:
    #branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Begin
      run: |
        pip3 install fonttools
        python3 ./buildAAttf.py

    - name: Upload to release
      uses: ncipollo/release-action@v1
      with:
        token: "${{ secrets.GITHUB_TOKEN }}"
        tag: "test-AA-ttf"
        artifacts: "*.7z"
        allowUpdates: true
#         draft: true
        name: "Build Test"
        body: "Advocate Ancient Sans TTF"


